# Generated by Django 4.2.4 on 2023-08-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_skils_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(default="Uganda", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(default="Kampala", max_length=255),
        ),
    ]
