# Generated by Django 4.2.4 on 2023-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_profile_country_profile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="experience",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
